### ISSUE TITLE
musyx ADSR to midi files

### ISSUE THREAD

**Issue by derselbst** [AxioDL/amuse#5]
Any chance to write the musyx ADSR events to the midi file, using custom defined MIDI CCs?

**Comment by jackoalan** [comment]
MusyX already has a mode for this, activated by the SETADSRCTRL command (used extensively by Starfox Adventures)

I'd rather not add a secondary hack to support a feature that already exists; especially considering the behavior of the SoundMacros are heavily affected by envelope timings. 

Keep an eye on the project though, eventually we will be adding SoundMacro editing tools. After that, you will be able to customise the sound well beyond envelope controls.

**Comment by derselbst** [comment]
Sry, think you misunderstood me: I was talking about using amuseconv to convert musyx songs (midi.wad from SFA indeed) to midi files. When doing so, there currently seems to be no way that the SETADSRCTRL cmds get converted to some MIDI CCs.

E.g. when the attack time gets changed by SETADSRCTRL, amuseconv would write a CC23 event with an appropriate value to the midi file, so soundfonts can make use of that and adjust the attack time correspondingly.

**Comment by derselbst** [comment]
omg, you're right, you already do that. Got myself confused, sorry.

**Comment by derselbst** [comment]
But how do I know which of them gets mapped to which MIDI CC? Since this seems to directly depend on whatever is given by the musyx sng file. So is there a common rule that e.g. attack is always mapped to some specific CC?

**Comment by jackoalan** [comment]
I wish there was more predictablity to MusyX SNG playback myself. In reality, the sound designers of the specific game have full say over what CCs are used in SETADSRCTRL (assuming it's used at all).

The big issue is there isn't a predictable way to relate SNG data with the SoundMacros (which occurs per-note, and SoundMacros can also spawn other SoundMacros with PLAYMACRO).

SoundMacros are Turing-Complete by design, prompting the adage:
![soundmacros](https://i.imgflip.com/1b2xwz.jpg)

The only way to get any meaningful data from the SoundMacros is to render them out, ultimately flattening the data into a sound mix (in an optimal manner for a game console).

**Comment by Antidote** [comment]
Factor 5 created a bit of a monster with SoundMacros, as jack said, they're _entirely_ non-trivial due to their Turing-Completeness. Amuse adds a bit of extensibility to the overall design that Vanilla MusyX didn't have, but it's by no means a magic wand. That being said any ideas that involve extending the MusyX proper are more than welcome, however anything that requires any interaction with SoundMacros on _any_ level needs to be approached with a great deal of scrutiny and care.

**Comment by derselbst** [comment]
Ok, thanks so far!
